"""add role column to users

Revision ID: 216d6dd440d5
Revises: 6e3c95c988d2
Create Date: 2025-10-01 11:31:48.472850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216d6dd440d5'
down_revision: Union[str, Sequence[str], None] = '6e3c95c988d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add role column (nullable first)
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # Set default 'customer' for existing users
    op.execute("UPDATE users SET role = 'customer' WHERE role IS NULL")
    
    # Make it NOT NULL
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
